name: Configure environment
description: Prepare build environment with a common steps

inputs:
  ansiblePythonInterpreter:
    description: Location of python interpreter
    required: false
    default: '/opt/pipx/venvs/ansible-core/bin/python'
  botSshKey:
    description: BOT's SSH key used for interact with GitHub
    required: true
    default: ''
  githubToken:
    description: GitHub token
    required: true
    default: ''
  dependenciesList:
    description: The list of dependencies that are needed to be installed
    required: true
    default: 'boto3 botocore stringcase troposphere requests'

runs:
  using: composite
  steps:
    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'

    - name: Configure GitHub credentials
      run: git config --global url."https://${{ inputs.githubToken }}@github.com/".insteadOf "https://github.com/"

    - name: Install dependencies
      run: poetry install --with dev,testing,codestyle,deployment --no-interaction

    - name: Install Ansible dependencies
      run: pip --python ${{ inputs.ansiblePythonInterpreter }} install ${{ inputs.dependenciesList }}

    - name: Install SSH Key
      run: |
        mkdir ~/.ssh && chmod 700 ~/.ssh
        echo "${{ inputs.botSshKey }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_rsa

    - name: Install any galaxy modules
      run: |
        test -f ansible/requirements.yml && \
        ansible-galaxy install -r ansible/requirements.yml --force || \
        echo "Nothing to install - skipping!"
